/*
 * This source file was generated by the Gradle 'init' task
 */
package pertemuan1;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import pertemuan1.repository.*;
import pertemuan1.services.*;

public class App {

    public JurusanRepository jurusanRepository = new JurusanRepository();
    public MahasiswaRepository mahasiswaRepository = new MahasiswaRepository(jurusanRepository);
    public MatakuliahRepository matakuliahRepository = new MatakuliahRepository(jurusanRepository);
    public EnrollmentRepository enrollmentRepository = new EnrollmentRepository();

    public static List<String> listIndexNilai = Arrays.asList("A", "A-", "B+", "B", "B-", "C+", "C", "D", "E");
    public static Map<String, Double> indexNilaiValue = Map.of(
            "A", 4.0,
            "A-", 3.7,
            "B+", 3.3,
            "B", 3.0,
            "B-", 2.7,
            "C+", 2.3,
            "C", 2.0,
            "D", 1.0,
            "E", 0.0);

    public static void handleMenuJurusan(JurusanRepository jurusanRepository) {
        JurusanServices.printMenuJurusan();
        int input = appUtils.readInt();
        while (input != 0) {
            switch (input) {
                case 1 -> {
                    JurusanServices.displayAllJurusan(jurusanRepository);
                    break;
                }
                case 2 -> {
                    JurusanServices.addJurusan(jurusanRepository);
                    break;
                }
                case 3 -> {
                    JurusanServices.editJurusan(jurusanRepository);
                    break;
                }
                case 4 -> {
                    JurusanServices.deleteJurusan(jurusanRepository);
                    break;
                }
                default -> {
                    break;
                }
            }
            JurusanServices.printMenuJurusan();
            input = appUtils.readInt();
        }
    }

    public static void handleMenuMataKuliah(MatakuliahRepository matakuliahRepository,
            JurusanRepository jurusanRepository) {
        MataKuliahServices.printMenuMataKuliah();
        int input = appUtils.readInt();
        while (input != 0) {
            switch (input) {
                case 1 -> {
                    MataKuliahServices.listMataKuliahByJurusan(matakuliahRepository);
                    break;
                }
                case 2 -> {
                    MataKuliahServices.addMataKuliah(matakuliahRepository, jurusanRepository);
                    break;
                }
                case 3 -> {
                    MataKuliahServices.editMataKuliah(matakuliahRepository, jurusanRepository);
                    break;
                }
                case 4 -> {
                    MataKuliahServices.deleteMataKuliah(matakuliahRepository);
                    break;
                }
                default -> {
                    break;
                }
            }
            MataKuliahServices.printMenuMataKuliah();
            input = appUtils.readInt();
        }
    }

    public static void handleMenuMahasiswa(MatakuliahRepository matakuliahRepository,
            JurusanRepository jurusanRepository, MahasiswaRepository mahasiswaRepository,
            EnrollmentRepository enrollmentRepository) {
        MahasiswaService.printMenuMahasiswa();
        int input = appUtils.readInt();
        while (input != 0) {
            switch (input) {
                case 1 -> {
                    MahasiswaService.displayAll(mahasiswaRepository);
                    break;
                }
                case 2 -> {
                    MahasiswaService.addNew(mahasiswaRepository, jurusanRepository);
                    break;
                }
                case 3 -> {
                    MahasiswaService.edit(mahasiswaRepository, jurusanRepository);
                    break;
                }
                case 4 -> {
                    MahasiswaService.delete(mahasiswaRepository);
                    break;
                }
                case 5 -> {
                    MahasiswaService.addGrade(mahasiswaRepository, matakuliahRepository, null, listIndexNilai);
                    break;
                }
                case 6 -> {
                    MahasiswaService.calculateIpk(enrollmentRepository, indexNilaiValue);
                    break;
                }
                default -> {
                    break;
                }
            }
            MahasiswaService.printMenuMahasiswa();
            input = appUtils.readInt();
        }
    }

    public static void printMenuUtama() {
        System.out.println("");
        System.out.println("Menu utama: ");
        System.out.println("1. Menu jurusan");
        System.out.println("2. Menu mata kuliah");
        System.out.println("3. Menu mahasiswa");
        System.out.println("0. Keluar ");
    }

    public void run() {
        printMenuUtama();
        int input = appUtils.readInt();
        while (input != 0) {
            switch (input) {
                case 1 -> {
                    handleMenuJurusan(this.jurusanRepository);
                    break;
                }
                case 2 -> {
                    handleMenuMataKuliah(this.matakuliahRepository, this.jurusanRepository);
                    break;
                }
                case 3 -> {
                    handleMenuMahasiswa(this.matakuliahRepository, this.jurusanRepository, this.mahasiswaRepository,
                            this.enrollmentRepository);
                    break;
                }
                default -> {
                    break;
                }
            }
            printMenuUtama();
            input = appUtils.readInt();
        }
    }

    public static void main(String[] args) {
        App miniSIAApp = new App();
        miniSIAApp.run();
    }
}
